// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXgJrequyph9ZggVwjnlPjzQ9i87urgi0',
    appId: '1:352867316217:web:3e8d92ec1f46f5cbcf4d28',
    messagingSenderId: '352867316217',
    projectId: 'skillswap-ec546',
    authDomain: 'skillswap-ec546.firebaseapp.com',
    storageBucket: 'skillswap-ec546.firebasestorage.app',
    measurementId: 'G-XLJDNN73H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGxms6vmMrzAuuQ1FgLX0-TS0w9adtz7g',
    appId: '1:352867316217:android:e7838060ba46f4cfcf4d28',
    messagingSenderId: '352867316217',
    projectId: 'skillswap-ec546',
    storageBucket: 'skillswap-ec546.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1KWOKNjpAzNSi0_HugHUIbNX9764er6w',
    appId: '1:352867316217:ios:31a9dfae7862aa27cf4d28',
    messagingSenderId: '352867316217',
    projectId: 'skillswap-ec546',
    storageBucket: 'skillswap-ec546.firebasestorage.app',
    iosClientId: '352867316217-1i8du98227qqph88q5e1s3hq4rfm5rob.apps.googleusercontent.com',
    iosBundleId: 'com.example.skillSwap',
  );
}
